defaults: &defaults
  working_directory: ~/markovmodel/PyEMMA
  docker:
    - image: continuumio/miniconda3

version: 2
jobs:
  build:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - run: git fetch --unshallow || true
      - run: conda config --add channels conda-forge
      - run: conda config --set always_yes true
      - run: conda config --set quiet true
      - run: conda install conda-build
      - run: conda install scipy;
      - run: conda install numpy;
      - run: conda install numba;
      - run: conda install dask;
      - run: apt-get update
      - run: apt-get install -y gcc
      - run: apt-get install -y libx11-6 python-dev git build-essential
      - run: apt-get install -y autoconf automake gcc g++ make gfortran
      #- run: pip install git+https://github.com/russelljjarvis/neuronunit@dev
      - run: pip install pip --upgrade;
      - run: pip install neo
      - run: pip install cython
      - run: pip install neuronunitopt==0.19
      - run: pip install git+https://github.com/russelljjarvis/BluePyOpt@neuronunit_reduced_cells
      #- run: pip install git+https://github.com/russelljjarvis/neuronunit@optimization
      - run: pip install git+https://github.com/russelljjarvis/sciunit@dev
      - run: pip install -r requirements.txt;
      - run: pip install -e .;
      - run: python unittest/test_run.py
